import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "./global.css";
import Lottie from "./assets/register_lottie";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Registration Page',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className="h-full bg-gray dark:bg-gray-900">

            <div className="mx-auto ">
                <div className="flex justify-center px-6 py-12">

                    <div className="w-full xl:w-3/4 lg:w-11/12 flex" style={{ maxHeight: "600px" }}>

                        {/* <div
                            className="w-full h-auto bg-gray-400 dark:bg-gray-800 hidden lg:block lg:w-5/12 bg-cover rounded-l-lg"
                            style={{ backgroundImage: 'url("https://img.freepik.com/premium-photo/funny-minimalist-design-with-floating-human-brain-wearing-sunglasses-against-blue-background-ideas-creativity-intellect-artificial-intelligence_410516-1290.jpg")', backgroundSize: 'cover', backgroundPosition: 'center' }}
                        ></div> */}
                        <div
                            className="w-full h-auto bg-blue-500 bg-opacity-70  dark:bg-gray-800 hidden lg:block lg:w-6/12 bg-cover rounded-l-lg"
                            style={{  backgroundSize: 'cover', backgroundPosition: 'center'}}
                        ><Lottie ></Lottie></div>

                        {children}


                    </div>
                </div>
            </div>
        </div>
    )
}
// https://img.freepik.com/premium-photo/funny-minimalist-design-with-floating-human-brain-wearing-sunglasses-against-blue-background-ideas-creativity-intellect-artificial-intelligence_410516-1290.jpg