import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "./global.css";
import Lottie from "./assets/register_lottie";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Registration Page',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
      
        <div className="min-h-screen bg-white">

        <div className="mx-auto bg-white">
            <div className="flex justify-center px-6 py-12 bg-white">

                <div className="h-full w-full bg-white xl:w-3/4 lg:w-11/12 flex" style={{ maxHeight: "600px" }}>

                    <div
                        className="w-full h-auto lg:w-6/12 lg:flex-shrink-0 bg-blue-500 bg-opacity-70 dark:bg-gray-800 lg:block hidden md:flex"
                        style={{ backgroundSize: 'cover', backgroundPosition: 'center', alignItems: 'center' }}
                    >
                        <Lottie />
                    </div>

                    {children}

                </div>
            </div>
        </div>
    </div>
    )
 }
 // style={{ backgroundSize: 'cover', backgroundPosition: 'center', alignItems: 'center' }}
// https://img.freepik.com/premium-photo/funny-minimalist-design-with-floating-human-brain-wearing-sunglasses-against-blue-background-ideas-creativity-intellect-artificial-intelligence_410516-1290.jpg
